# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configuracion.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63onfiguracion.proto\"\x17\n\x04\x46ile\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"6\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x13\n\x04\x66ile\x18\x02 \x01(\x0b\x32\x05.File\"!\n\x0eUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\'\n\x10\x44ownloadResponse\x12\x13\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x05.File2i\n\x0b\x46ileService\x12)\n\x06Upload\x12\x0e.UploadRequest\x1a\x0f.UploadResponse\x12/\n\x08\x44ownload\x12\x10.DownloadRequest\x1a\x11.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'configuracion_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILE']._serialized_start=23
  _globals['_FILE']._serialized_end=46
  _globals['_UPLOADREQUEST']._serialized_start=48
  _globals['_UPLOADREQUEST']._serialized_end=102
  _globals['_UPLOADRESPONSE']._serialized_start=104
  _globals['_UPLOADRESPONSE']._serialized_end=137
  _globals['_DOWNLOADREQUEST']._serialized_start=139
  _globals['_DOWNLOADREQUEST']._serialized_end=174
  _globals['_DOWNLOADRESPONSE']._serialized_start=176
  _globals['_DOWNLOADRESPONSE']._serialized_end=215
  _globals['_FILESERVICE']._serialized_start=217
  _globals['_FILESERVICE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
